# Generated by Django 2.0.5 on 2018-10-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASGS_Mon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_name',
            field=models.CharField(default='michael_instance', max_length=100),
            preserve_default=False,
        ),
    ]
