# Generated by Django 2.0.8 on 2019-03-14 16:29

from django.db import migrations, models
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('ASGS_Mon', '0003_instance_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Json',
            fields=[
                ('data', models.CharField(max_length = 4000)),
            ],
        ),
        migrations.CreateModel(
            name='User_pref',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length = 150)),
                ('home_site', models.IntegerField()),
                ('filter_site', JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat_message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length = 150)),
                ('message', models.CharField(max_length = 150)),
                ('msg_ts', models.DateTimeField()),
            ],
        ),
    ]
