# Generated by Django 2.0.5 on 2018-10-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASGS_Mon', '0004_auto_20190314_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_pct_complete',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
