# Generated by Django 2.0.8 on 2021-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASGS_Mon', '0007_auto_20210914_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor_config',
            name='command_line',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='supervisor_config',
            name='command_matrix',
            field=models.CharField(max_length=300),
        ),
    ]
