/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 20-Sep-2018 11:01:13 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS asgs_mon_event_id_seq
;

DROP SEQUENCE IF EXISTS asgs_mon_event_group_id_seq
;

DROP SEQUENCE IF EXISTS asgs_mon_instance_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS ASGS_Mon_event CASCADE
;

DROP TABLE IF EXISTS ASGS_Mon_event_group CASCADE
;

DROP TABLE IF EXISTS ASGS_Mon_event_type_lu CASCADE
;

DROP TABLE IF EXISTS ASGS_Mon_instance CASCADE
;

DROP TABLE IF EXISTS ASGS_Mon_instance_state_type_lu CASCADE
;

DROP TABLE IF EXISTS ASGS_Mon_site_lu CASCADE
;

DROP TABLE IF EXISTS ASGS_Mon_state_type_lu CASCADE
;

/* Create Tables */

CREATE TABLE ASGS_Mon_event
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"asgs_mon_event_id_seq"'::text)::regclass),
	site_id integer NOT NULL,
	event_group_id integer NOT NULL,
	event_type_id integer NOT NULL,
	event_ts date NOT NULL,
	advisory_id varchar(50) NOT NULL,
	pct_complete integer NOT NULL,
	process varchar(100) NOT NULL,
	raw_data varchar(4000) NULL
)
;

CREATE TABLE ASGS_Mon_event_group
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"asgs_mon_event_group_id_seq"'::text)::regclass),
	instance_id integer NOT NULL,
	state_type_id integer NOT NULL,
	event_group_ts date NOT NULL,
	storm_name varchar(50) NOT NULL,
	storm_number varchar(50) NOT NULL,
	advisory_id varchar(50) NOT NULL,
	final_product varchar(1000) NULL
)
;

CREATE TABLE ASGS_Mon_event_type_lu
(
	id integer NOT NULL,
	name varchar(50) NOT NULL,
	description varchar(100) NULL
)
;

CREATE TABLE ASGS_Mon_instance
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"asgs_mon_instance_id_seq"'::text)::regclass),
	inst_state_type integer NULL,
	process_id integer NULL,
	site_id integer NULL,
	start_ts date NULL,
	end_ts date NULL,
	run_params varchar(100) NULL
	instance_name varchar(100) NULL
)
;

CREATE TABLE ASGS_Mon_instance_state_type_lu
(
	id integer NOT NULL,
	name varchar(50) NOT NULL,
	description varchar(100) NULL
)
;

CREATE TABLE ASGS_Mon_site_lu
(
	id integer NOT NULL,
	name varchar(50) NOT NULL,
	description varchar(100) NULL,
	tech_contact varchar(100) NOT NULL,
	phys_location varchar(100) NOT NULL,
	cluster_name varchar(100) NOT NULL
)
;

CREATE TABLE ASGS_Mon_state_type_lu
(
	id integer NOT NULL,
	name text NOT NULL,
	description text NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE ASGS_Mon_event ADD CONSTRAINT PK_event
	PRIMARY KEY (id)
;

ALTER TABLE ASGS_Mon_event_group ADD CONSTRAINT PK_ASGS_Mon_event_group
	PRIMARY KEY (id)
;

ALTER TABLE ASGS_Mon_event_type_lu ADD CONSTRAINT PK_event_type_lu
	PRIMARY KEY (id)
;

ALTER TABLE ASGS_Mon_instance ADD CONSTRAINT PK_ASGS_Mon_instance
	PRIMARY KEY (id)
;

ALTER TABLE ASGS_Mon_instance_state_type_lu ADD CONSTRAINT PK_event_type_lu
	PRIMARY KEY (id)
;

ALTER TABLE ASGS_Mon_site_lu ADD CONSTRAINT PK_site_lu
	PRIMARY KEY (id)
;

ALTER TABLE ASGS_Mon_state_type_lu ADD CONSTRAINT PK_event_type_lu
	PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE ASGS_Mon_event ADD CONSTRAINT FK_ASGS_Mon_event_ASGS_Mon_event_group
	FOREIGN KEY (event_group_id) REFERENCES ASGS_Mon_event_group (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ASGS_Mon_event ADD CONSTRAINT FK_ASGS_Mon_event_ASGS_Mon_site_lu
	FOREIGN KEY (site_id) REFERENCES ASGS_Mon_site_lu (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ASGS_Mon_event_group ADD CONSTRAINT FK_ASGS_Mon_event_group_ASGS_Mon_state_type_lu
	FOREIGN KEY (state_type_id) REFERENCES ASGS_Mon_state_type_lu (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ASGS_Mon_instance ADD CONSTRAINT FK_ASGS_Mon_instance_ASGS_Mon_instance_state_type_lu
	FOREIGN KEY (inst_state_type) REFERENCES ASGS_Mon_instance_state_type_lu (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE asgs_mon_event_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE asgs_mon_event_group_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE asgs_mon_instance_id_seq INCREMENT 1 START 1
;
