/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 30-Apr-2018 4:21:43 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'event'
;

DROP TABLE IF EXISTS 'event_type_lu'
;

DROP TABLE IF EXISTS 'message'
;

DROP TABLE IF EXISTS 'message_type_lu'
;

DROP TABLE IF EXISTS 'site_lu'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'event'
(
	'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'site_id' INTEGER NOT NULL,
	'event_type_id' INTEGER NOT NULL,
	'message_id' INTEGER NOT NULL,
	'event_ts' TEXT NOT NULL,
	'nodes_in_use' INTEGER NOT NULL,
	'nodes_available' INTEGER NOT NULL,
	'raw_data' TEXT NOT NULL,
	CONSTRAINT 'FK_event_event_type_lu' FOREIGN KEY ('event_type_id') REFERENCES 'event_type_lu' ('id') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_event_message' FOREIGN KEY ('message_id') REFERENCES 'message' ('id') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_event_site_lu' FOREIGN KEY ('site_id') REFERENCES 'site_lu' ('id') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'event_type_lu'
(
	'id' INTEGER NOT NULL PRIMARY KEY,
	'name' TEXT NOT NULL,
	'description' TEXT NULL
)
;

CREATE TABLE 'message'
(
	'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'message_type_id' INTEGER NULL,
	'advisory_id' TEXT NULL,
	'storm_name' TEXT NULL,
	'storm_number' INTEGER NULL,
	'message' TEXT NULL,
	'other' TEXT NULL,
	CONSTRAINT 'FK_message_message_type_lu' FOREIGN KEY ('message_type_id') REFERENCES 'message_type_lu' ('id') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'message_type_lu'
(
	'id' INTEGER NOT NULL PRIMARY KEY,
	'name' TEXT NOT NULL,
	'description' TEXT NULL
)
;

CREATE TABLE 'site_lu'
(
	'id' INTEGER NOT NULL PRIMARY KEY,
	'name' TEXT NOT NULL,
	'description' TEXT NULL,
	'nodes' INTEGER NOT NULL,
	'tech_contact' TEXT NOT NULL,
	'location' TEXT NULL
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_event_event_type_lu'
 ON 'event' ('event_type_id' ASC)
;

CREATE INDEX 'IXFK_event_message'
 ON 'event' ('message_id' ASC)
;

CREATE INDEX 'IXFK_event_site_lu'
 ON 'event' ('site_id' ASC)
;

CREATE INDEX 'IXFK_message_message_type_lu'
 ON 'message' ('message_type_id' ASC)
;
