# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

name: Build/push the Docker image

# working parameters that are specific to this script
env:
  REGISTRY: containers.renci.org/eds/asgs_monitor_ui

# trigger event is manual
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

# job definition
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # job steps
    steps:
      # checkout the codebase
      - name: Checkout
        uses: actions/checkout@v1

      # connect to the renci image registry
      - name: Login to containers.renci.org
        uses: docker/login-action@v2
        with:
          registry: containers.renci.org
          username: ${{ secrets.USER }}
          password: ${{ secrets.PW }}
      
      # get the tag for the image
      - name: Get the version
        id: get_version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
      
      # build and push the image. The docker v3 action automatically handles the git checkout.
      - name: Build/Push the image to the registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}:latest
            ${{ env.REGISTRY }}:${{ steps.get_version.outputs.VERSION }}
